### ISSUE TITLE
line 103: syntax error: unexpected redirection

### ISSUE THREAD

**Issue by cdhigh** [nitefood/ai-bash-gpt#3]
I execute the script in Kindle terminal emulador Kterm, It throws an erro:
line 103: syntax error: unexpected redirection

The code line is:
input=$(jq ".[-$CONVERSATION_BUFFER_LEN:]" <<<"$@")

Is It for bash or Kterm?
Is It fixable?
Thinks.

**Comment by nitefood** [comment]
That line contains a [here string](https://tldp.org/LDP/abs/html/x17837.html), which (unlike heredocs) is unsupported on posix-compliant shells. I have no experience with Kterm specifically, but are you sure that BASH is available on your system?

**Comment by cdhigh** [comment]
cmd "echo $0" returns:
/bin/sh

you are right, there is no bash in there.
sh can support the script?
