### ISSUE TITLE
parse json error

### ISSUE THREAD

**Issue by cdhigh** [nitefood/ai-bash-gpt#4]
Is there a way to perform pre-escaping of characters when using non-english (portugues etc), which contains some non-ASCII characters like ç, ã, õ, etc.?
Sometimes, JSON parsing errors occur that prevent the display of ChatGPT's responses, for example:
`jq: parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 13, column 93.`

Is there any method for pre-escaping?

edited:
If there are special characters in the text that needs to be sent, this error can also occur.

**Comment by cdhigh** [comment]
I found some unicode strings in conversations.json.
[conversations.json.zip](https://github.com/nitefood/ai-bash-gpt/files/11852925/conversations.json.zip)

Is it because the file was saved using Unicode encoding, and the decoding failed due to the lack of the original encoding during reading?

**Comment by nitefood** [comment]
I suspect the unicode encoding in the conversations.json file you attached are more likely due to keystrokes you (maybe inadvertently) sent while interacting with the script, rather than non-printable characters being part of the conversation.
I used your json and could playback the chats just fine, can't reproduce the `jq` error you got in the first post. I also tried starting a new conversation using the characters you mentioned specifically, without any issues. Can you please tell me the steps to reproduce this `jq` error?

**Comment by nitefood** [comment]
Here's the test I did:

![image](https://github.com/nitefood/ai-bash-gpt/assets/24555810/aa1ac944-eec9-4d44-b44b-00252635f6e9)

**Comment by cdhigh** [comment]
Enter "como dancar lindo" to reproduce the issue.

![jq](https://github.com/nitefood/ai-bash-gpt/assets/2580077/e3210ad9-13d8-4143-ac19-2a742a706834)

**Comment by nitefood** [comment]
Sorry, I can't reproduce. Just copy/pasted the sentece you suggested several times and got no errors. May this have to do with the Kindle underlying OS? Maybe a localization issue? Have you tried defaulting to a UTF-8 locale? I have my default locale set on `en_US.UTF-8` if that may help.

![image](https://github.com/nitefood/ai-bash-gpt/assets/24555810/4a2c7c4a-1df2-4dc9-bea6-e7f4c45504da)

![image](https://github.com/nitefood/ai-bash-gpt/assets/24555810/0f7fd84d-ee79-4f41-a920-42280eb1e05a)

![image](https://github.com/nitefood/ai-bash-gpt/assets/24555810/239c87a6-59dd-44c8-95d4-74f1d29ecce3)

**Comment by nitefood** [comment]
> Or can you remove all characters less than 0x1f from the user-entered string?

that should not be necessary since the script already "stringifies" the input using `jq -Rs` [here](https://github.com/nitefood/ai-bash-gpt/blob/22e77b1a0c8c1aab6a2ea7fdcfa0a018b42e62a2/ai#L628-L632) - that include handling special characters whose value is less than 0x1f, e.g. 0xA for newline (LF)

**Comment by cdhigh** [comment]
I tried some tricks by searching on google, still no luck.
Are we able to determine which one is causing the error among multiple jq statements in the code?

**Comment by nitefood** [comment]
you may try to run the script using `bash -x ai "como dancar lindo"` to see exactly what gets called, which variables get set and all the output.

**Comment by cdhigh** [comment]
caught this line!
https://github.com/nitefood/ai-bash-gpt/blob/22e77b1a0c8c1aab6a2ea7fdcfa0a018b42e62a2/ai#L735C5-L735C61
735    response_text=$(jq -r '.content' <<<"$response_message")

![jq2](https://github.com/nitefood/ai-bash-gpt/assets/2580077/75bc651a-7781-4af9-9009-bb24242eeab1)

**Comment by nitefood** [comment]
you may try placing a `hexdump -C <<<"$response_message"` before that line to see exactly what control character `jq` is complaining about, then run the script normally

**Comment by cdhigh** [comment]
a lot of pages, can hexdump to a file?

**Comment by cdhigh** [comment]
complaining in line 17 col 178.

[rsphexdump.txt](https://github.com/nitefood/ai-bash-gpt/files/11856535/rsphexdump.txt)

**Comment by cdhigh** [comment]
This is another dump, line 11 col 151.

[rsphexdump (1).txt](https://github.com/nitefood/ai-bash-gpt/files/11856653/rsphexdump.1.txt)

**Comment by cdhigh** [comment]
After continuous searching and experimentation, it was discovered that the error was caused by a restriction in the JSON data where line breaks were not allowed. If a line break was present, it needed to be escaped. 
By modifying the following line of code: 
https://github.com/nitefood/ai-bash-gpt/blob/22e77b1a0c8c1aab6a2ea7fdcfa0a018b42e62a2/ai#L735C5-L735C61
`735 response_text=$(jq -r '.content' <<<"$response_message")
`to 
`response_text=$(jq -Rnr '[inputs] | join("\\n") | fromjson | .content' <<<"$response_message")
`
The issue was totally resolved!

The code line is come from [stackoverflow](https://stackoverflow.com/questions/51628133/parse-error-when-text-is-split-on-multi-lines-control-characters-from-u0000-t).

However, I am still don't know of the exact meaning of the modified line of code~~~
